# Generated by Django 4.0 on 2022-01-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_guest_show_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='company',
            field=models.CharField(default='Blank', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
