# Generated by Django 4.0 on 2022-01-13 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='recuriter',
            new_name='recruiter',
        ),
    ]
